name: Deploy to VPS (Dev)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/dev-diuacm
            php artisan down || true
            if [ ! -f .env ]; then
              cp .env.example .env
            fi
            git pull origin dev
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            php artisan clear-compiled
            php artisan optimize
            npm ci
            npm run build
            php artisan migrate --force
            php artisan up
